### ISSUE TITLE
Add Travis configuration for running tests

### ISSUE THREAD

**Issue by ehuisman** [NitorCreations/vault#11]

**Comment by jsyrjala** [comment]
There has been a travis build for java for more than 6 months now. No support for node it seems.

**Comment by psiniemi** [comment]
There should be a travis conf that runs the cli with javascript and java and python and verifies that all functionality works accross any language (e.g. write java and read python and delete javascript etc.)

**Comment by Esgrove** [comment]
We now have integration tests with GitHub Actions for cross-checking vault implementations
