### ISSUE TITLE
nodejs implementation should look up bucket and key names from the CloudFormation stack if not specified

### ISSUE THREAD

**Issue by psiniemi** [NitorCreations/vault#15]
Only region should be mandatory and is often specified in the environment.

**Comment by psiniemi** [comment]
See https://github.com/NitorCreations/vault/blob/master/python/n_vault/vault.py#L28

**Comment by ehuisman** [comment]
I've been working on this today. The asynchronous nature of the `aws-sdk` and the limitations of `aws-sdk-mock` have made it harder than I'd prefer.

**Comment by jsyrjala** [comment]
Needed also for integration testing #25

**Comment by ehuisman** [comment]
Closed by #43
