### ISSUE TITLE
With MacOS request take a long time to complete

### ISSUE THREAD

**Issue by jsyrjala** [NitorCreations/vault#20]
The vault is executing `http://169.254.169.254/latest/dynamic/instance-identity/document` to determine if it is running in AWS. This takes about 1 minute to complete via timeout in MacOS.
This happens every time you execute a vault cli command.

The workaround is set AWS_DEFAULT_REGION env. 
```
export AWS_DEFAULT_REGION=eu-central-1
```

Having a default region defined in `~/.aws/config` is not enough for some reason.

**Comment by jsyrjala** [comment]
Commit a9c9be0728ce05a22d5dcac3e34a26f46a2a3b4d fixes this

**Comment by psiniemi** [comment]
Fixed in 0.16
